docker:
  languages:
    golang:
      default_image: "latest"
      base_image: "golang:{{ .version }}-alpine" # docker image
      entrypoint: [] # exec

      # language resource limits(cover the global configuration)
      limits:
        memory_mb: 1024
        cpu_time: 60